### ISSUE TITLE
Reference of MF model

### ISSUE THREAD

**Issue by JacksonWuxs** [noveens/reviews4rec#4]
Hi Noveen,

I am very appreciating to this repo! As a beginner in Recommendation System, this repo gives me a lot helps.
But, your implement of MF model makes me confuse, hope you can give me some hints.

As far as we know, the basic BiasMF should be `y=global_bias + user_bias + item_bias + pq` which is proposed by Y. Koren et al., (2009). However, your default setting of `MF` doesn't work like this, in contrast, your setting of `MF_dot` is following the reference. Could you provide some references about your implement of `MF` model? Or, you can update your reference list in your readme: https://github.com/noveens/reviews4rec#run-instructions.

Waiting to your response!

Best,
Xuansheng

**Comment by noveens** [comment]
Hi @JacksonWuxs ,

Thanks for your clarification! I should've probably done a better job explaining the difference between these two.
Just to confirm --- `MF_dot` specifies the original, linear MF specification; whereas, `MF` represents the MLP-only version proposed in the NeuMF [paper](https://arxiv.org/pdf/1708.05031.pdf).

I updated the README as you suggested, thanks for the suggestion!

**Comment by JacksonWuxs** [comment]
Hi @noveens,

Thanks to your quickly response! Your explanation works to me!
